In [26]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv('../Data/Insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [27]:
df['sex'] = df['sex'].map({'female': 0, 'male': 1})
df['smoker'] = df['smoker'].map({'yes': 0, 'no': 1})
df['region'] = df['region'].map({'southwest': 0, 'southeast': 1, 'northwest': 2, 'northeast': 3})
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       0       0  16884.92400
1   18    1  33.770         1       1       1   1725.55230
2   28    1  33.000         3       1       1   4449.46200
3   33    1  22.705         0       1       2  21984.47061
4   32    1  28.880         0       1       2   3866.85520

In [28]:
x = df.iloc[:, :-1].values
y = np.array(df['charges'].values).reshape(-1,1).ravel()

In [29]:
from sklearn.model_selection import   train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [30]:
model = RandomForestRegressor(random_state=0, n_estimators=10)
model.fit(x_train, y_train)
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.96486691927533
0.8707158987742302

In [ ]:
new_df = pd.DataFrame([{
    'age': int(input('Enter age: ')),
    'sex': input('male[1]/female[0]: '),
    'bmi': float(input('Enter BMI: ')),
    'children': int(input('Enter number of children: ')),
    'smoker': input('smoker[1]/not smoker[0]: '),
    'region': input('southwest[0]/southeast[1]/northwest[2]/northeast[3]: ')
}])
prediction = model.predict(new_df)
print(prediction[0])

ValueError: X has 1 features, but RandomForestRegressor is expecting 6 features as input.